// <auto-generated />
using ConsoleApp1.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20230807145227_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.20");

            modelBuilder.Entity("ConsoleApp1.Data", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data10")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data6")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data7")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data8")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data9")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Datas");
                });
#pragma warning restore 612, 618
        }
    }
}
